// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migraciones por conexión directa/session (DIRECT_URL): el transaction
    // pooler que usa el runtime no soporta los advisory locks de migrate.
    url: env("DIRECT_URL"),
  },
});
